/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dLdx_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[4] = {1, 1, 0, 0};
static const casadi_int casadi_s4[66] = {1, 32, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 25, 26, 27, 28, 29, 30, 31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* jac_L:(X[12],dX[12],k,t,XChief[6],out_CurveLength[1x1,0nz])->(jac[1x32,31nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a13, a130, a131, a132, a133, a134, a135, a136, a137, a138, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[4]? arg[4][1] : 0;
  a1=arg[4]? arg[4][5] : 0;
  a2=(a0*a1);
  a3=arg[4]? arg[4][2] : 0;
  a4=arg[4]? arg[4][4] : 0;
  a5=(a3*a4);
  a2=(a2-a5);
  a5=casadi_sq(a2);
  a6=arg[4]? arg[4][3] : 0;
  a7=(a3*a6);
  a8=arg[4]? arg[4][0] : 0;
  a9=(a8*a1);
  a7=(a7-a9);
  a9=casadi_sq(a7);
  a5=(a5+a9);
  a9=(a8*a4);
  a10=(a0*a6);
  a9=(a9-a10);
  a10=casadi_sq(a9);
  a5=(a5+a10);
  a5=sqrt(a5);
  a10=(a2/a5);
  a11=-2.;
  a12=(a8*a6);
  a13=(a0*a4);
  a12=(a12+a13);
  a13=(a3*a1);
  a12=(a12+a13);
  a12=(a11*a12);
  a13=(a0*a1);
  a14=(a3*a4);
  a13=(a13-a14);
  a14=(a12*a13);
  a15=casadi_sq(a8);
  a16=casadi_sq(a0);
  a15=(a15+a16);
  a16=casadi_sq(a3);
  a15=(a15+a16);
  a16=casadi_sq(a15);
  a14=(a14/a16);
  a17=(a10*a14);
  a18=(a7/a5);
  a19=(a3*a6);
  a20=(a8*a1);
  a19=(a19-a20);
  a20=(a12*a19);
  a20=(a20/a16);
  a21=(a18*a20);
  a17=(a17+a21);
  a21=(a9/a5);
  a22=(a8*a4);
  a23=(a0*a6);
  a22=(a22-a23);
  a23=(a12*a22);
  a23=(a23/a16);
  a24=(a21*a23);
  a17=(a17+a24);
  a24=1.6840054676261389e+04;
  a25=arg[1]? arg[1][4] : 0;
  a26=-3.9860044150000002e+05;
  a27=sqrt(a15);
  a28=arg[0]? arg[0][0] : 0;
  a29=(a27+a28);
  a30=casadi_sq(a29);
  a31=arg[0]? arg[0][1] : 0;
  a32=casadi_sq(a31);
  a30=(a30+a32);
  a32=arg[0]? arg[0][2] : 0;
  a33=casadi_sq(a32);
  a30=(a30+a33);
  a33=sqrt(a30);
  a34=(a33*a30);
  a35=(a26/a34);
  a36=(a35*a31);
  a37=(a13/a15);
  a38=(a10*a37);
  a39=(a19/a15);
  a40=(a18*a39);
  a38=(a38+a40);
  a40=(a22/a15);
  a41=(a21*a40);
  a38=(a38+a41);
  a41=(a11*a38);
  a42=arg[0]? arg[0][3] : 0;
  a43=(a41*a42);
  a44=casadi_sq(a8);
  a45=casadi_sq(a0);
  a44=(a44+a45);
  a45=casadi_sq(a3);
  a44=(a44+a45);
  a44=sqrt(a44);
  a45=(a8/a44);
  a46=(a45*a37);
  a47=(a0/a44);
  a48=(a47*a39);
  a46=(a46+a48);
  a48=(a3/a44);
  a49=(a48*a40);
  a46=(a46+a49);
  a49=(a11*a46);
  a50=arg[0]? arg[0][5] : 0;
  a51=(a49*a50);
  a43=(a43-a51);
  a51=(a18*a48);
  a52=(a21*a47);
  a51=(a51-a52);
  a52=casadi_sq(a51);
  a53=(a21*a45);
  a54=(a10*a48);
  a53=(a53-a54);
  a54=casadi_sq(a53);
  a52=(a52+a54);
  a54=(a10*a47);
  a55=(a18*a45);
  a54=(a54-a55);
  a55=casadi_sq(a54);
  a52=(a52+a55);
  a52=sqrt(a52);
  a55=(a51/a52);
  a56=(a55*a37);
  a57=(a53/a52);
  a58=(a57*a39);
  a56=(a56+a58);
  a58=(a54/a52);
  a59=(a58*a40);
  a56=(a56+a59);
  a59=(a56*a32);
  a60=(a38*a31);
  a59=(a59-a60);
  a60=(a38*a59);
  a61=(a46*a31);
  a62=(a56*a28);
  a61=(a61-a62);
  a62=(a46*a61);
  a60=(a60-a62);
  a43=(a43-a60);
  a60=(a17*a28);
  a62=(a45*a14);
  a63=(a47*a20);
  a62=(a62+a63);
  a63=(a48*a23);
  a62=(a62+a63);
  a63=(a62*a32);
  a60=(a60-a63);
  a43=(a43-a60);
  a36=(a36+a43);
  a36=(a24*a36);
  a25=(a25-a36);
  a25=(a25+a25);
  a36=(a24*a25);
  a43=(a17*a36);
  a60=(a55*a14);
  a63=(a57*a20);
  a60=(a60+a63);
  a63=(a58*a23);
  a60=(a60+a63);
  a63=arg[1]? arg[1][5] : 0;
  a64=(a35*a32);
  a65=(a11*a46);
  a66=arg[0]? arg[0][4] : 0;
  a67=(a65*a66);
  a68=(a11*a56);
  a69=(a68*a42);
  a67=(a67-a69);
  a69=(a38*a28);
  a70=(a46*a32);
  a69=(a69-a70);
  a70=(a46*a69);
  a71=(a56*a59);
  a70=(a70-a71);
  a67=(a67-a70);
  a70=(a62*a31);
  a71=(a60*a28);
  a70=(a70-a71);
  a67=(a67-a70);
  a64=(a64+a67);
  a64=(a24*a64);
  a63=(a63-a64);
  a63=(a63+a63);
  a64=(a24*a63);
  a67=(a60*a64);
  a43=(a43-a67);
  a67=(a46*a64);
  a70=arg[1]? arg[1][3] : 0;
  a71=(a35*a29);
  a72=3.9860044150000002e+05;
  a73=(a72/a15);
  a71=(a71+a73);
  a74=(a11*a56);
  a75=(a74*a50);
  a76=(a11*a38);
  a77=(a76*a66);
  a75=(a75-a77);
  a77=(a56*a61);
  a78=(a38*a69);
  a77=(a77-a78);
  a75=(a75-a77);
  a77=(a60*a32);
  a78=(a17*a31);
  a77=(a77-a78);
  a75=(a75-a77);
  a71=(a71+a75);
  a71=(a24*a71);
  a70=(a70-a71);
  a70=(a70+a70);
  a71=(a24*a70);
  a75=(a38*a71);
  a67=(a67-a75);
  a75=(a38*a67);
  a43=(a43+a75);
  a75=(a56*a71);
  a77=(a46*a36);
  a75=(a75-a77);
  a77=(a56*a75);
  a43=(a43-a77);
  a77=(a29+a29);
  a34=(a35/a34);
  a78=(a32*a64);
  a79=(a31*a36);
  a78=(a78+a79);
  a29=(a29*a71);
  a78=(a78+a29);
  a34=(a34*a78);
  a78=(a33*a34);
  a30=(a30*a34);
  a33=(a33+a33);
  a30=(a30/a33);
  a78=(a78+a30);
  a77=(a77*a78);
  a30=(a35*a71);
  a77=(a77-a30);
  a43=(a43+a77);
  if (res[0]!=0) res[0][0]=a43;
  a43=(a62*a64);
  a30=(a38*a36);
  a33=(a56*a64);
  a30=(a30-a33);
  a38=(a38*a30);
  a43=(a43-a38);
  a38=(a35*a36);
  a43=(a43-a38);
  a17=(a17*a71);
  a43=(a43-a17);
  a17=(a46*a75);
  a43=(a43+a17);
  a17=(a31+a31);
  a17=(a17*a78);
  a43=(a43+a17);
  if (res[0]!=0) res[0][1]=a43;
  a56=(a56*a30);
  a35=(a35*a64);
  a62=(a62*a36);
  a35=(a35+a62);
  a56=(a56-a35);
  a60=(a60*a71);
  a56=(a56+a60);
  a46=(a46*a67);
  a56=(a56-a46);
  a46=(a32+a32);
  a46=(a46*a78);
  a56=(a56+a46);
  if (res[0]!=0) res[0][2]=a56;
  a68=(a68*a64);
  a41=(a41*a36);
  a68=(a68-a41);
  a41=arg[1]? arg[1][0] : 0;
  a56=(a24*a42);
  a46=(a41-a56);
  a78=arg[2]? arg[2][0] : 0;
  a60=(a46*a78);
  a41=(a41-a56);
  a41=(a78*a41);
  a56=(a60+a41);
  a56=(a24*a56);
  a68=(a68-a56);
  if (res[0]!=0) res[0][3]=a68;
  a76=(a76*a71);
  a65=(a65*a64);
  a76=(a76-a65);
  a65=arg[1]? arg[1][1] : 0;
  a68=(a24*a66);
  a56=(a65-a68);
  a35=(a56*a78);
  a65=(a65-a68);
  a65=(a78*a65);
  a68=(a35+a65);
  a68=(a24*a68);
  a76=(a76-a68);
  if (res[0]!=0) res[0][4]=a76;
  a49=(a49*a36);
  a74=(a74*a71);
  a49=(a49-a74);
  a74=arg[1]? arg[1][2] : 0;
  a76=(a24*a50);
  a68=(a74-a76);
  a62=(a68*a78);
  a74=(a74-a76);
  a74=(a78*a74);
  a76=(a62+a74);
  a76=(a24*a76);
  a49=(a49-a76);
  if (res[0]!=0) res[0][5]=a49;
  a49=(a0*a1);
  a76=(a3*a4);
  a49=(a49-a76);
  a76=casadi_sq(a49);
  a43=(a3*a6);
  a17=(a8*a1);
  a43=(a43-a17);
  a17=casadi_sq(a43);
  a76=(a76+a17);
  a17=(a8*a4);
  a38=(a0*a6);
  a17=(a17-a38);
  a38=casadi_sq(a17);
  a76=(a76+a38);
  a76=sqrt(a76);
  a38=(a49/a76);
  a33=(a8*a6);
  a34=(a0*a4);
  a33=(a33+a34);
  a34=(a3*a1);
  a33=(a33+a34);
  a33=(a11*a33);
  a34=(a0*a1);
  a29=(a3*a4);
  a34=(a34-a29);
  a29=(a33*a34);
  a79=casadi_sq(a8);
  a80=casadi_sq(a0);
  a79=(a79+a80);
  a80=casadi_sq(a3);
  a79=(a79+a80);
  a80=casadi_sq(a79);
  a29=(a29/a80);
  a81=(a38*a29);
  a82=(a43/a76);
  a83=(a3*a6);
  a84=(a8*a1);
  a83=(a83-a84);
  a84=(a33*a83);
  a84=(a84/a80);
  a85=(a82*a84);
  a81=(a81+a85);
  a85=(a17/a76);
  a86=(a8*a4);
  a87=(a0*a6);
  a86=(a86-a87);
  a87=(a33*a86);
  a87=(a87/a80);
  a88=(a85*a87);
  a81=(a81+a88);
  a88=arg[1]? arg[1][10] : 0;
  a89=sqrt(a79);
  a90=arg[0]? arg[0][6] : 0;
  a91=(a89+a90);
  a92=casadi_sq(a91);
  a93=arg[0]? arg[0][7] : 0;
  a94=casadi_sq(a93);
  a92=(a92+a94);
  a94=arg[0]? arg[0][8] : 0;
  a95=casadi_sq(a94);
  a92=(a92+a95);
  a95=sqrt(a92);
  a96=(a95*a92);
  a26=(a26/a96);
  a97=(a26*a93);
  a98=(a34/a79);
  a99=(a38*a98);
  a100=(a83/a79);
  a101=(a82*a100);
  a99=(a99+a101);
  a101=(a86/a79);
  a102=(a85*a101);
  a99=(a99+a102);
  a102=(a11*a99);
  a103=arg[0]? arg[0][9] : 0;
  a104=(a102*a103);
  a105=casadi_sq(a8);
  a106=casadi_sq(a0);
  a105=(a105+a106);
  a106=casadi_sq(a3);
  a105=(a105+a106);
  a105=sqrt(a105);
  a106=(a8/a105);
  a107=(a106*a98);
  a108=(a0/a105);
  a109=(a108*a100);
  a107=(a107+a109);
  a109=(a3/a105);
  a110=(a109*a101);
  a107=(a107+a110);
  a110=(a11*a107);
  a111=arg[0]? arg[0][11] : 0;
  a112=(a110*a111);
  a104=(a104-a112);
  a112=(a82*a109);
  a113=(a85*a108);
  a112=(a112-a113);
  a113=casadi_sq(a112);
  a114=(a85*a106);
  a115=(a38*a109);
  a114=(a114-a115);
  a115=casadi_sq(a114);
  a113=(a113+a115);
  a115=(a38*a108);
  a116=(a82*a106);
  a115=(a115-a116);
  a116=casadi_sq(a115);
  a113=(a113+a116);
  a113=sqrt(a113);
  a116=(a112/a113);
  a117=(a116*a98);
  a118=(a114/a113);
  a119=(a118*a100);
  a117=(a117+a119);
  a119=(a115/a113);
  a120=(a119*a101);
  a117=(a117+a120);
  a120=(a117*a94);
  a121=(a99*a93);
  a120=(a120-a121);
  a121=(a99*a120);
  a122=(a107*a93);
  a123=(a117*a90);
  a122=(a122-a123);
  a123=(a107*a122);
  a121=(a121-a123);
  a104=(a104-a121);
  a121=(a81*a90);
  a123=(a106*a29);
  a124=(a108*a84);
  a123=(a123+a124);
  a124=(a109*a87);
  a123=(a123+a124);
  a124=(a123*a94);
  a121=(a121-a124);
  a104=(a104-a121);
  a97=(a97+a104);
  a97=(a24*a97);
  a88=(a88-a97);
  a88=(a88+a88);
  a97=(a24*a88);
  a104=(a81*a97);
  a121=(a116*a29);
  a124=(a118*a84);
  a121=(a121+a124);
  a124=(a119*a87);
  a121=(a121+a124);
  a124=arg[1]? arg[1][11] : 0;
  a125=(a26*a94);
  a126=(a11*a107);
  a127=arg[0]? arg[0][10] : 0;
  a128=(a126*a127);
  a129=(a11*a117);
  a130=(a129*a103);
  a128=(a128-a130);
  a130=(a99*a90);
  a131=(a107*a94);
  a130=(a130-a131);
  a131=(a107*a130);
  a132=(a117*a120);
  a131=(a131-a132);
  a128=(a128-a131);
  a131=(a123*a93);
  a132=(a121*a90);
  a131=(a131-a132);
  a128=(a128-a131);
  a125=(a125+a128);
  a125=(a24*a125);
  a124=(a124-a125);
  a124=(a124+a124);
  a125=(a24*a124);
  a128=(a121*a125);
  a104=(a104-a128);
  a128=(a107*a125);
  a131=arg[1]? arg[1][9] : 0;
  a132=(a26*a91);
  a72=(a72/a79);
  a132=(a132+a72);
  a133=(a11*a117);
  a134=(a133*a111);
  a135=(a11*a99);
  a136=(a135*a127);
  a134=(a134-a136);
  a136=(a117*a122);
  a137=(a99*a130);
  a136=(a136-a137);
  a134=(a134-a136);
  a136=(a121*a94);
  a137=(a81*a93);
  a136=(a136-a137);
  a134=(a134-a136);
  a132=(a132+a134);
  a132=(a24*a132);
  a131=(a131-a132);
  a131=(a131+a131);
  a132=(a24*a131);
  a134=(a99*a132);
  a128=(a128-a134);
  a134=(a99*a128);
  a104=(a104+a134);
  a134=(a117*a132);
  a136=(a107*a97);
  a134=(a134-a136);
  a136=(a117*a134);
  a104=(a104-a136);
  a136=(a91+a91);
  a96=(a26/a96);
  a137=(a94*a125);
  a138=(a93*a97);
  a137=(a137+a138);
  a91=(a91*a132);
  a137=(a137+a91);
  a96=(a96*a137);
  a137=(a95*a96);
  a92=(a92*a96);
  a95=(a95+a95);
  a92=(a92/a95);
  a137=(a137+a92);
  a136=(a136*a137);
  a92=(a26*a132);
  a136=(a136-a92);
  a104=(a104+a136);
  if (res[0]!=0) res[0][6]=a104;
  a104=(a123*a125);
  a92=(a99*a97);
  a95=(a117*a125);
  a92=(a92-a95);
  a99=(a99*a92);
  a104=(a104-a99);
  a99=(a26*a97);
  a104=(a104-a99);
  a81=(a81*a132);
  a104=(a104-a81);
  a81=(a107*a134);
  a104=(a104+a81);
  a81=(a93+a93);
  a81=(a81*a137);
  a104=(a104+a81);
  if (res[0]!=0) res[0][7]=a104;
  a117=(a117*a92);
  a26=(a26*a125);
  a123=(a123*a97);
  a26=(a26+a123);
  a117=(a117-a26);
  a121=(a121*a132);
  a117=(a117+a121);
  a107=(a107*a128);
  a117=(a117-a107);
  a107=(a94+a94);
  a107=(a107*a137);
  a117=(a117+a107);
  if (res[0]!=0) res[0][8]=a117;
  a129=(a129*a125);
  a102=(a102*a97);
  a129=(a129-a102);
  a102=arg[1]? arg[1][6] : 0;
  a117=(a24*a103);
  a107=(a102-a117);
  a137=(a107*a78);
  a102=(a102-a117);
  a102=(a78*a102);
  a117=(a137+a102);
  a117=(a24*a117);
  a129=(a129-a117);
  if (res[0]!=0) res[0][9]=a129;
  a135=(a135*a132);
  a126=(a126*a125);
  a135=(a135-a126);
  a126=arg[1]? arg[1][7] : 0;
  a129=(a24*a127);
  a117=(a126-a129);
  a121=(a117*a78);
  a126=(a126-a129);
  a126=(a78*a126);
  a129=(a121+a126);
  a129=(a24*a129);
  a135=(a135-a129);
  if (res[0]!=0) res[0][10]=a135;
  a110=(a110*a97);
  a133=(a133*a132);
  a110=(a110-a133);
  a133=arg[1]? arg[1][8] : 0;
  a135=(a24*a111);
  a129=(a133-a135);
  a26=(a129*a78);
  a133=(a133-a135);
  a78=(a78*a133);
  a133=(a26+a78);
  a24=(a24*a133);
  a110=(a110-a24);
  if (res[0]!=0) res[0][11]=a110;
  a60=(a60+a41);
  if (res[0]!=0) res[0][12]=a60;
  a35=(a35+a65);
  if (res[0]!=0) res[0][13]=a35;
  a62=(a62+a74);
  if (res[0]!=0) res[0][14]=a62;
  if (res[0]!=0) res[0][15]=a70;
  if (res[0]!=0) res[0][16]=a25;
  if (res[0]!=0) res[0][17]=a63;
  a137=(a137+a102);
  if (res[0]!=0) res[0][18]=a137;
  a121=(a121+a126);
  if (res[0]!=0) res[0][19]=a121;
  a26=(a26+a78);
  if (res[0]!=0) res[0][20]=a26;
  if (res[0]!=0) res[0][21]=a131;
  if (res[0]!=0) res[0][22]=a88;
  if (res[0]!=0) res[0][23]=a124;
  a129=casadi_sq(a129);
  a117=casadi_sq(a117);
  a129=(a129+a117);
  a107=casadi_sq(a107);
  a129=(a129+a107);
  a68=casadi_sq(a68);
  a129=(a129+a68);
  a56=casadi_sq(a56);
  a129=(a129+a56);
  a46=casadi_sq(a46);
  a129=(a129+a46);
  if (res[0]!=0) res[0][24]=a129;
  a129=(a93*a125);
  a46=(a94*a97);
  a129=(a129-a46);
  a46=(a109*a129);
  a56=(a90*a97);
  a68=(a93*a132);
  a56=(a56-a68);
  a68=(a85*a56);
  a46=(a46+a68);
  a68=(a94*a132);
  a107=(a90*a125);
  a68=(a68-a107);
  a107=(a119*a68);
  a46=(a46+a107);
  a107=(a46/a80);
  a86=(a86*a107);
  a117=(a108*a129);
  a124=(a82*a56);
  a117=(a117+a124);
  a124=(a118*a68);
  a117=(a117+a124);
  a124=(a117/a80);
  a83=(a83*a124);
  a86=(a86+a83);
  a83=(a106*a129);
  a88=(a38*a56);
  a83=(a83+a88);
  a88=(a116*a68);
  a83=(a83+a88);
  a88=(a83/a80);
  a34=(a34*a88);
  a86=(a86+a34);
  a86=(a11*a86);
  a34=(a6*a86);
  a107=(a33*a107);
  a131=(a130*a125);
  a26=(a127*a125);
  a26=(a11*a26);
  a131=(a131-a26);
  a26=(a122*a97);
  a131=(a131-a26);
  a26=(a111*a97);
  a26=(a11*a26);
  a131=(a131+a26);
  a26=(a94*a128);
  a131=(a131-a26);
  a26=(a93*a134);
  a131=(a131+a26);
  a26=(a109*a131);
  a78=(a120*a97);
  a93=(a93*a92);
  a78=(a78-a93);
  a97=(a103*a97);
  a97=(a11*a97);
  a78=(a78-a97);
  a130=(a130*a132);
  a78=(a78-a130);
  a128=(a90*a128);
  a78=(a78+a128);
  a127=(a127*a132);
  a127=(a11*a127);
  a78=(a78+a127);
  a127=(a85*a78);
  a26=(a26+a127);
  a103=(a103*a125);
  a103=(a11*a103);
  a120=(a120*a125);
  a103=(a103-a120);
  a94=(a94*a92);
  a103=(a103+a94);
  a122=(a122*a132);
  a103=(a103+a122);
  a90=(a90*a134);
  a103=(a103-a90);
  a111=(a111*a132);
  a111=(a11*a111);
  a103=(a103-a111);
  a111=(a119*a103);
  a26=(a26+a111);
  a111=(a26/a79);
  a107=(a107+a111);
  a111=(a4*a107);
  a34=(a34+a111);
  a124=(a33*a124);
  a111=(a108*a131);
  a90=(a82*a78);
  a111=(a111+a90);
  a90=(a118*a103);
  a111=(a111+a90);
  a90=(a111/a79);
  a124=(a124+a90);
  a90=(a1*a124);
  a34=(a34-a90);
  a90=(a29*a129);
  a134=(a98*a131);
  a90=(a90+a134);
  a134=(a87*a68);
  a122=(a101*a103);
  a134=(a134+a122);
  a122=(a134/a113);
  a115=(a115+a115);
  a119=(a119/a113);
  a119=(a119*a134);
  a118=(a118/a113);
  a134=(a84*a68);
  a94=(a100*a103);
  a134=(a134+a94);
  a118=(a118*a134);
  a119=(a119+a118);
  a118=(a116/a113);
  a68=(a29*a68);
  a94=(a98*a103);
  a68=(a68+a94);
  a118=(a118*a68);
  a119=(a119+a118);
  a118=(a113+a113);
  a119=(a119/a118);
  a115=(a115*a119);
  a122=(a122-a115);
  a115=(a82*a122);
  a90=(a90-a115);
  a134=(a134/a113);
  a114=(a114+a114);
  a114=(a114*a119);
  a134=(a134-a114);
  a114=(a85*a134);
  a90=(a90+a114);
  a114=(a90/a105);
  a34=(a34+a114);
  a114=(a8+a8);
  a115=(a106/a105);
  a115=(a115*a90);
  a90=(a108/a105);
  a118=(a84*a129);
  a94=(a100*a131);
  a118=(a118+a94);
  a94=(a38*a122);
  a118=(a118+a94);
  a68=(a68/a113);
  a112=(a112+a112);
  a112=(a112*a119);
  a68=(a68-a112);
  a112=(a85*a68);
  a118=(a118-a112);
  a90=(a90*a118);
  a115=(a115+a90);
  a90=(a109/a105);
  a129=(a87*a129);
  a112=(a101*a131);
  a129=(a129+a112);
  a112=(a38*a134);
  a129=(a129-a112);
  a112=(a82*a68);
  a129=(a129+a112);
  a90=(a90*a129);
  a115=(a115+a90);
  a90=(a105+a105);
  a115=(a115/a90);
  a114=(a114*a115);
  a34=(a34-a114);
  a114=(a87*a56);
  a90=(a101*a78);
  a114=(a114+a90);
  a90=(a106*a134);
  a114=(a114+a90);
  a90=(a108*a68);
  a114=(a114-a90);
  a90=(a114/a76);
  a17=(a17+a17);
  a112=(a38/a76);
  a119=(a29*a56);
  a113=(a98*a78);
  a119=(a119+a113);
  a108=(a108*a122);
  a119=(a119+a108);
  a134=(a109*a134);
  a119=(a119-a134);
  a112=(a112*a119);
  a85=(a85/a76);
  a85=(a85*a114);
  a112=(a112+a85);
  a82=(a82/a76);
  a56=(a84*a56);
  a85=(a100*a78);
  a56=(a56+a85);
  a122=(a106*a122);
  a56=(a56-a122);
  a109=(a109*a68);
  a56=(a56+a109);
  a82=(a82*a56);
  a112=(a112+a82);
  a82=(a76+a76);
  a112=(a112/a82);
  a17=(a17*a112);
  a90=(a90-a17);
  a17=(a4*a90);
  a34=(a34+a17);
  a56=(a56/a76);
  a43=(a43+a43);
  a43=(a43*a112);
  a56=(a56-a43);
  a43=(a1*a56);
  a34=(a34-a43);
  a43=(a8+a8);
  a72=(a72/a79);
  a72=(a72*a132);
  a132=(a79+a79);
  a87=(a87/a80);
  a87=(a87*a46);
  a84=(a84/a80);
  a84=(a84*a117);
  a87=(a87+a84);
  a29=(a29/a80);
  a29=(a29*a83);
  a87=(a87+a29);
  a132=(a132*a87);
  a101=(a101/a79);
  a101=(a101*a26);
  a132=(a132+a101);
  a100=(a100/a79);
  a100=(a100*a111);
  a132=(a132+a100);
  a98=(a98/a79);
  a106=(a106*a131);
  a38=(a38*a78);
  a106=(a106+a38);
  a116=(a116*a103);
  a106=(a106+a116);
  a98=(a98*a106);
  a132=(a132+a98);
  a72=(a72-a132);
  a89=(a89+a89);
  a136=(a136/a89);
  a72=(a72+a136);
  a43=(a43*a72);
  a34=(a34+a43);
  a43=(a31*a64);
  a136=(a32*a36);
  a43=(a43-a136);
  a136=(a48*a43);
  a89=(a28*a36);
  a132=(a31*a71);
  a89=(a89-a132);
  a132=(a21*a89);
  a136=(a136+a132);
  a132=(a32*a71);
  a98=(a28*a64);
  a132=(a132-a98);
  a98=(a58*a132);
  a136=(a136+a98);
  a98=(a136/a16);
  a22=(a22*a98);
  a116=(a47*a43);
  a103=(a18*a89);
  a116=(a116+a103);
  a103=(a57*a132);
  a116=(a116+a103);
  a103=(a116/a16);
  a19=(a19*a103);
  a22=(a22+a19);
  a19=(a45*a43);
  a38=(a10*a89);
  a19=(a19+a38);
  a38=(a55*a132);
  a19=(a19+a38);
  a38=(a19/a16);
  a13=(a13*a38);
  a22=(a22+a13);
  a22=(a11*a22);
  a13=(a6*a22);
  a34=(a34+a13);
  a98=(a12*a98);
  a13=(a69*a64);
  a78=(a66*a64);
  a78=(a11*a78);
  a13=(a13-a78);
  a78=(a61*a36);
  a13=(a13-a78);
  a78=(a50*a36);
  a78=(a11*a78);
  a13=(a13+a78);
  a78=(a32*a67);
  a13=(a13-a78);
  a78=(a31*a75);
  a13=(a13+a78);
  a78=(a48*a13);
  a131=(a59*a36);
  a31=(a31*a30);
  a131=(a131-a31);
  a36=(a42*a36);
  a36=(a11*a36);
  a131=(a131-a36);
  a69=(a69*a71);
  a131=(a131-a69);
  a67=(a28*a67);
  a131=(a131+a67);
  a66=(a66*a71);
  a66=(a11*a66);
  a131=(a131+a66);
  a66=(a21*a131);
  a78=(a78+a66);
  a42=(a42*a64);
  a42=(a11*a42);
  a59=(a59*a64);
  a42=(a42-a59);
  a32=(a32*a30);
  a42=(a42+a32);
  a61=(a61*a71);
  a42=(a42+a61);
  a28=(a28*a75);
  a42=(a42-a28);
  a50=(a50*a71);
  a11=(a11*a50);
  a42=(a42-a11);
  a11=(a58*a42);
  a78=(a78+a11);
  a11=(a78/a15);
  a98=(a98+a11);
  a11=(a4*a98);
  a34=(a34+a11);
  a103=(a12*a103);
  a11=(a47*a13);
  a50=(a18*a131);
  a11=(a11+a50);
  a50=(a57*a42);
  a11=(a11+a50);
  a50=(a11/a15);
  a103=(a103+a50);
  a50=(a1*a103);
  a34=(a34-a50);
  a50=(a14*a43);
  a28=(a37*a13);
  a50=(a50+a28);
  a28=(a23*a132);
  a75=(a40*a42);
  a28=(a28+a75);
  a75=(a28/a52);
  a54=(a54+a54);
  a58=(a58/a52);
  a58=(a58*a28);
  a57=(a57/a52);
  a28=(a20*a132);
  a61=(a39*a42);
  a28=(a28+a61);
  a57=(a57*a28);
  a58=(a58+a57);
  a57=(a55/a52);
  a132=(a14*a132);
  a61=(a37*a42);
  a132=(a132+a61);
  a57=(a57*a132);
  a58=(a58+a57);
  a57=(a52+a52);
  a58=(a58/a57);
  a54=(a54*a58);
  a75=(a75-a54);
  a54=(a18*a75);
  a50=(a50-a54);
  a28=(a28/a52);
  a53=(a53+a53);
  a53=(a53*a58);
  a28=(a28-a53);
  a53=(a21*a28);
  a50=(a50+a53);
  a53=(a50/a44);
  a34=(a34+a53);
  a53=(a8+a8);
  a54=(a45/a44);
  a54=(a54*a50);
  a50=(a47/a44);
  a57=(a20*a43);
  a61=(a39*a13);
  a57=(a57+a61);
  a61=(a10*a75);
  a57=(a57+a61);
  a132=(a132/a52);
  a51=(a51+a51);
  a51=(a51*a58);
  a132=(a132-a51);
  a51=(a21*a132);
  a57=(a57-a51);
  a50=(a50*a57);
  a54=(a54+a50);
  a50=(a48/a44);
  a43=(a23*a43);
  a51=(a40*a13);
  a43=(a43+a51);
  a51=(a10*a28);
  a43=(a43-a51);
  a51=(a18*a132);
  a43=(a43+a51);
  a50=(a50*a43);
  a54=(a54+a50);
  a50=(a44+a44);
  a54=(a54/a50);
  a53=(a53*a54);
  a34=(a34-a53);
  a53=(a23*a89);
  a50=(a40*a131);
  a53=(a53+a50);
  a50=(a45*a28);
  a53=(a53+a50);
  a50=(a47*a132);
  a53=(a53-a50);
  a50=(a53/a5);
  a9=(a9+a9);
  a51=(a10/a5);
  a58=(a14*a89);
  a52=(a37*a131);
  a58=(a58+a52);
  a47=(a47*a75);
  a58=(a58+a47);
  a28=(a48*a28);
  a58=(a58-a28);
  a51=(a51*a58);
  a21=(a21/a5);
  a21=(a21*a53);
  a51=(a51+a21);
  a18=(a18/a5);
  a89=(a20*a89);
  a21=(a39*a131);
  a89=(a89+a21);
  a75=(a45*a75);
  a89=(a89-a75);
  a48=(a48*a132);
  a89=(a89+a48);
  a18=(a18*a89);
  a51=(a51+a18);
  a18=(a5+a5);
  a51=(a51/a18);
  a9=(a9*a51);
  a50=(a50-a9);
  a9=(a4*a50);
  a34=(a34+a9);
  a89=(a89/a5);
  a7=(a7+a7);
  a7=(a7*a51);
  a89=(a89-a7);
  a7=(a1*a89);
  a34=(a34-a7);
  a7=(a8+a8);
  a73=(a73/a15);
  a73=(a73*a71);
  a71=(a15+a15);
  a23=(a23/a16);
  a23=(a23*a136);
  a20=(a20/a16);
  a20=(a20*a116);
  a23=(a23+a20);
  a14=(a14/a16);
  a14=(a14*a19);
  a23=(a23+a14);
  a71=(a71*a23);
  a40=(a40/a15);
  a40=(a40*a78);
  a71=(a71+a40);
  a39=(a39/a15);
  a39=(a39*a11);
  a71=(a71+a39);
  a37=(a37/a15);
  a45=(a45*a13);
  a10=(a10*a131);
  a45=(a45+a10);
  a55=(a55*a42);
  a45=(a45+a55);
  a37=(a37*a45);
  a71=(a71+a37);
  a73=(a73-a71);
  a27=(a27+a27);
  a77=(a77/a27);
  a73=(a73+a77);
  a7=(a7*a73);
  a34=(a34+a7);
  if (res[0]!=0) res[0][25]=a34;
  a34=(a4*a86);
  a7=(a6*a107);
  a34=(a34-a7);
  a33=(a33*a88);
  a106=(a106/a79);
  a33=(a33+a106);
  a106=(a1*a33);
  a34=(a34+a106);
  a118=(a118/a105);
  a34=(a34+a118);
  a118=(a0+a0);
  a118=(a118*a115);
  a34=(a34-a118);
  a118=(a6*a90);
  a34=(a34-a118);
  a119=(a119/a76);
  a49=(a49+a49);
  a49=(a49*a112);
  a119=(a119-a49);
  a49=(a1*a119);
  a34=(a34+a49);
  a49=(a0+a0);
  a49=(a49*a72);
  a34=(a34+a49);
  a49=(a4*a22);
  a34=(a34+a49);
  a49=(a6*a98);
  a34=(a34-a49);
  a12=(a12*a38);
  a45=(a45/a15);
  a12=(a12+a45);
  a45=(a1*a12);
  a34=(a34+a45);
  a57=(a57/a44);
  a34=(a34+a57);
  a57=(a0+a0);
  a57=(a57*a54);
  a34=(a34-a57);
  a57=(a6*a50);
  a34=(a34-a57);
  a58=(a58/a5);
  a2=(a2+a2);
  a2=(a2*a51);
  a58=(a58-a2);
  a2=(a1*a58);
  a34=(a34+a2);
  a2=(a0+a0);
  a2=(a2*a73);
  a34=(a34+a2);
  if (res[0]!=0) res[0][26]=a34;
  a34=(a1*a86);
  a2=(a6*a124);
  a34=(a34+a2);
  a2=(a4*a33);
  a34=(a34-a2);
  a129=(a129/a105);
  a34=(a34+a129);
  a129=(a3+a3);
  a129=(a129*a115);
  a34=(a34-a129);
  a129=(a4*a119);
  a34=(a34-a129);
  a129=(a6*a56);
  a34=(a34+a129);
  a129=(a3+a3);
  a129=(a129*a72);
  a34=(a34+a129);
  a1=(a1*a22);
  a34=(a34+a1);
  a1=(a6*a103);
  a34=(a34+a1);
  a1=(a4*a12);
  a34=(a34-a1);
  a43=(a43/a44);
  a34=(a34+a43);
  a43=(a3+a3);
  a43=(a43*a54);
  a34=(a34-a43);
  a4=(a4*a58);
  a34=(a34-a4);
  a6=(a6*a89);
  a34=(a34+a6);
  a6=(a3+a3);
  a6=(a6*a73);
  a34=(a34+a6);
  if (res[0]!=0) res[0][27]=a34;
  a34=(a8*a86);
  a6=(a0*a107);
  a34=(a34-a6);
  a6=(a3*a124);
  a34=(a34+a6);
  a6=(a0*a90);
  a34=(a34-a6);
  a6=(a3*a56);
  a34=(a34+a6);
  a6=(a8*a22);
  a34=(a34+a6);
  a6=(a0*a98);
  a34=(a34-a6);
  a6=(a3*a103);
  a34=(a34+a6);
  a6=(a0*a50);
  a34=(a34-a6);
  a6=(a3*a89);
  a34=(a34+a6);
  if (res[0]!=0) res[0][28]=a34;
  a34=(a0*a86);
  a107=(a8*a107);
  a34=(a34+a107);
  a107=(a3*a33);
  a34=(a34-a107);
  a90=(a8*a90);
  a34=(a34+a90);
  a90=(a3*a119);
  a34=(a34-a90);
  a90=(a0*a22);
  a34=(a34+a90);
  a98=(a8*a98);
  a34=(a34+a98);
  a98=(a3*a12);
  a34=(a34-a98);
  a50=(a8*a50);
  a34=(a34+a50);
  a50=(a3*a58);
  a34=(a34-a50);
  if (res[0]!=0) res[0][29]=a34;
  a86=(a3*a86);
  a124=(a8*a124);
  a86=(a86-a124);
  a33=(a0*a33);
  a86=(a86+a33);
  a119=(a0*a119);
  a86=(a86+a119);
  a56=(a8*a56);
  a86=(a86-a56);
  a3=(a3*a22);
  a86=(a86+a3);
  a103=(a8*a103);
  a86=(a86-a103);
  a12=(a0*a12);
  a86=(a86+a12);
  a0=(a0*a58);
  a86=(a86+a0);
  a8=(a8*a89);
  a86=(a86-a8);
  if (res[0]!=0) res[0][30]=a86;
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_L(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int jac_L_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_L_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_L_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int jac_L_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_L_release(int mem) {
}

CASADI_SYMBOL_EXPORT void jac_L_incref(void) {
}

CASADI_SYMBOL_EXPORT void jac_L_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int jac_L_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int jac_L_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real jac_L_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_L_name_in(casadi_int i){
  switch (i) {
    case 0: return "X";
    case 1: return "dX";
    case 2: return "k";
    case 3: return "t";
    case 4: return "XChief";
    case 5: return "out_CurveLength";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_L_name_out(casadi_int i){
  switch (i) {
    case 0: return "jac";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_L_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_L_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jac_L_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_jac_L(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[202];
  casadi_int *iw = 0;
  const casadi_real* arg[6] = {0};
  casadi_real* res[1] = {0};
  if (argc>6) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"jac_L\" failed. Too many input arguments (%d, max 6)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"jac_L\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+63);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+12, casadi_s0, w+63);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+24, casadi_s1, w+63);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+25, casadi_s1, w+63);
  if (--argc>=0) arg[4] = casadi_from_mex(argv[4], w+26, casadi_s2, w+63);
  if (--argc>=0) arg[5] = casadi_from_mex(argv[5], w+32, casadi_s3, w+63);
  --resc;
  res[0] = w+32;
  i = jac_L(arg, res, iw, w+63, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"jac_L\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s4, res[0]);
}
#endif

casadi_int main_jac_L(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[202];
  const casadi_real* arg[6];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+12;
  arg[2] = w+24;
  arg[3] = w+25;
  arg[4] = w+26;
  arg[5] = w+32;
  res[0] = w+32;
  a = w;
  for (j=0; j<32; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = jac_L(arg, res, iw, w+63, 0);
  if (flag) return flag;
  r = w+32;
  for (j=0; j<31; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[6];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_jac_L(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "jac_L")==0) {
    mex_jac_L(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'jac_L'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "jac_L")==0) {
    return main_jac_L(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'jac_L'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
